# Generated by Django 4.2 on 2023-04-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_zone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
