# Generated by Django 4.2 on 2023-04-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_zone', '0002_remove_message_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
